// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQI4GP_C9dbA4K5BHtgs4txWqTc9-m36g',
    appId: '1:826277795359:web:c7361e12358a73b90f672a',
    messagingSenderId: '826277795359',
    projectId: 'edutrack-7fdf6',
    authDomain: 'edutrack-7fdf6.firebaseapp.com',
    storageBucket: 'edutrack-7fdf6.firebasestorage.app',
    measurementId: 'G-1D056D2FL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJVSVHQcQmU5nwzV1ntL_Y_Ga1CGFKIFY',
    appId: '1:826277795359:android:5a8982791f1180e70f672a',
    messagingSenderId: '826277795359',
    projectId: 'edutrack-7fdf6',
    storageBucket: 'edutrack-7fdf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-pUdv80A4jeusy1dzc-W_teX6CvoDF7I',
    appId: '1:826277795359:ios:92c7b8d5a603e8bf0f672a',
    messagingSenderId: '826277795359',
    projectId: 'edutrack-7fdf6',
    storageBucket: 'edutrack-7fdf6.firebasestorage.app',
    iosBundleId: 'com.example.edutrackAdminWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-pUdv80A4jeusy1dzc-W_teX6CvoDF7I',
    appId: '1:826277795359:ios:92c7b8d5a603e8bf0f672a',
    messagingSenderId: '826277795359',
    projectId: 'edutrack-7fdf6',
    storageBucket: 'edutrack-7fdf6.firebasestorage.app',
    iosBundleId: 'com.example.edutrackAdminWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQI4GP_C9dbA4K5BHtgs4txWqTc9-m36g',
    appId: '1:826277795359:web:e616688f78152b6c0f672a',
    messagingSenderId: '826277795359',
    projectId: 'edutrack-7fdf6',
    authDomain: 'edutrack-7fdf6.firebaseapp.com',
    storageBucket: 'edutrack-7fdf6.firebasestorage.app',
    measurementId: 'G-Z754N0W9FJ',
  );
}
